services:
  db:
    image: postgres
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  api:
    build: ./backend/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    image: api
    platform: linux/amd64
    volumes:
      - ./backend:/backend
    environment:
      RAILS_ENV: development
    ports:
      - "3001:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./frontend:/frontend
    command: "yarn dev"
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
volumes:
  postgres_data:
